component: aws-dynamodb
name: trail-cam-image-table

inputs:
  name: ${name}-${stage}
  region: us-east-1
  # Don't delete the Database Table if "serverless remove" is run
  deletionPolicy: retain
  # Simple, single-table design
  attributeDefinitions:
    - AttributeName: key
      AttributeType: S
    - AttributeName: createdAt
      AttributeType: S
  keySchema:
    - AttributeName: key
      KeyType: HASH
    - AttributeName: createdAt
      KeyType: RANGE
