component: aws-dynamodb
name: trail-cam-user-table

inputs:
  name: ${name}-${stage}
  region: us-east-1
  # Don't delete the Database Table if "serverless remove" is run
  deletionPolicy: retain
  # Simple, single-table design
  attributeDefinitions:
    - AttributeName: email
      AttributeType: S
    - AttributeName: type
      AttributeType: S
    - AttributeName: id
      AttributeType: S
  keySchema:
    - AttributeName: email
      KeyType: HASH
    - AttributeName: type
      KeyType: RANGE
  globalSecondaryIndexes:
    - IndexName: gsi1
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
