Resources:
  InboxBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: ${self:custom.inboxBucket}
      PolicyDocument:
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - "${self:custom.inboxBucket}"
                  - "/*"
            Principal:
              Service:
                - ses.amazonaws.com
